name: iOS Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run iOS Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Run iOS tests
        run: |
          xcodebuild \
            -project SportApp.xcodeproj \
            -scheme SportApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0' \
            clean test | xcpretty && exit ${PIPESTATUS[0]}
