name: iOS Tests

on:
  pull_request:
    branches:
      - main        # или другая ветка, в которую приходят PR

jobs:
  test:
    name: Run iOS Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Run iOS tests
        run: |
          xcodebuild \
            -project SportApp.xcodeproj \
            -scheme SportApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            clean test | xcpretty && exit ${PIPESTATUS[0]}
